
package webservceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServceTest", targetNamespace = "http://webservce/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServceTest {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://webservce/", className = "webservceclient.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://webservce/", className = "webservceclient.GetMessageResponse")
    @Action(input = "http://webservce/ServceTest/getMessageRequest", output = "http://webservce/ServceTest/getMessageResponse")
    public String getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
